export const ADD_EMPLOYEES_LIST = 'ADD_EMPLOYEES_LIST';
export const DELETE_VACATION = 'DELETE_VACATION';
export const OPEN_EDIT_VACATION = 'OPEN_EDIT_VACATION';
export const CLOSE_EDIT_VACATION = 'CLOSE_EDIT_VACATION';
