export const ADD_EMPLOYEES_LIST = 'ADD_EMPLOYEES_LIST';
export const DELETE_VACATION = 'DELETE_VACATION';
export const OPEN_EDIT_VACATION = 'OPEN_EDIT_VACATION';
export const CLOSE_EDIT_VACATION = 'CLOSE_EDIT_VACATION';
export const SORT_BY_NAME = 'SORT_BY_NAME';
export const SORT_BY_DATE = 'SORT_BY_DATE';
